/// Flutter icons KarateShubudo
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KarateShubudo
///      fonts:
///       - asset: fonts/KarateShubudo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class KarateShubudo {
  KarateShubudo._();

  static const _kFontFam = 'KarateShubudo';
  static const String? _kFontPkg = null;

  static const IconData martial_belt = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
